import { AppRole, Permission } from "@/types/models";

export const ROLE_LABELS: Record<AppRole, string> = {
  super_admin: "Admin",
  admin: "Admin",
  principal: "Principal",
  teacher: "Teacher",
  accountant: "Accountant",
  parent: "Parent",
  student: "Student",
};

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  super_admin: [
    "dashboard:view", "students:view", "students:create", "students:edit", "students:delete",
    "teachers:view", "teachers:create", "teachers:edit", "teachers:delete",
    "classes:view", "classes:create", "classes:edit", "classes:delete",
    "attendance:view", "attendance:mark", "attendance:edit",
    "exams:view", "exams:create", "exams:edit", "exams:grade",
    "fees:view", "fees:create", "fees:collect", "fees:report",
    "timetable:view", "timetable:create", "timetable:edit",
    "announcements:view", "announcements:create", "announcements:edit", "announcements:delete",
    "reports:view", "reports:export",
    "settings:view", "settings:edit", "roles:manage", "audit:view",
    "parents:view", "parents:create", "parents:edit",
  ],
  admin: [
    "dashboard:view", "students:view", "students:create", "students:edit",
    "teachers:view", "teachers:create", "teachers:edit",
    "classes:view", "classes:create", "classes:edit",
    "attendance:view", "attendance:mark", "attendance:edit",
    "exams:view", "exams:create", "exams:edit", "exams:grade",
    "fees:view", "fees:create", "fees:collect", "fees:report",
    "timetable:view", "timetable:create", "timetable:edit",
    "announcements:view", "announcements:create", "announcements:edit",
    "reports:view", "reports:export",
    "settings:view", "settings:edit",
    "parents:view", "parents:create", "parents:edit",
    "audit:view",
  ],
  principal: [
    "dashboard:view", "students:view", "teachers:view",
    "classes:view", "attendance:view",
    "exams:view", "fees:view", "fees:report",
    "timetable:view",
    "announcements:view", "announcements:create", "announcements:edit",
    "reports:view", "reports:export",
    "settings:view", "audit:view",
    "parents:view",
  ],
  teacher: [
    "dashboard:view", "students:view",
    "classes:view", "attendance:view", "attendance:mark",
    "exams:view", "exams:grade",
    "timetable:view",
    "announcements:view",
  ],
  accountant: [
    "dashboard:view",
    "students:view",
    "fees:view", "fees:create", "fees:collect", "fees:report",
    "reports:view", "reports:export",
  ],
  parent: [
    "dashboard:view",
    "students:view",
    "attendance:view",
    "exams:view",
    "fees:view",
    "announcements:view",
  ],
  student: [
    "dashboard:view",
    "attendance:view",
    "exams:view",
    "fees:view",
    "timetable:view",
    "announcements:view",
  ],
};
